import {utils} from '@start9labs/start-sdk'
import {sdk} from '../sdk'
import {store} from '../fileModels/store'
import {i18n} from '../i18n'
const spec=sdk.InputSpec.of({regtest:sdk.Value.toggle({name:i18n("Use regtest (advanced)"),default:false}),pruned:sdk.Value.toggle({name:i18n("Use pruned-node adapter"),default:false}),rpc_url:sdk.Value.text({name:i18n("Knots RPC URL"),required:true,masked:false,default:''}),rpc_user:sdk.Value.text({name:i18n("RPC username"),required:true,masked:false,default:''}),rpc_password:sdk.Value.text({name:i18n("RPC password"),required:true,masked:true,default:''}),sweep_address:sdk.Value.text({name:i18n("Recovery sweep address"),required:true,masked:false,default:''}),recipient_keys:sdk.Value.text({name:i18n("Sideflash recipient public keys (comma or space separated)"),required:false,masked:false,default:''}),lightning:sdk.Value.toggle({name:i18n("Enable Lightning"),default:false}),cln_uri:sdk.Value.text({name:i18n("CLN gRPC URL"),required:false,masked:false,default:''}),hold_uri:sdk.Value.text({name:i18n("Hold gRPC URL"),required:false,masked:false,default:''}),ca:sdk.Value.text({name:i18n("CLN CA certificate (PEM)"),required:false,masked:false,default:''}),client_cert:sdk.Value.text({name:i18n("CLN client certificate (PEM)"),required:false,masked:false,default:''}),client_key:sdk.Value.text({name:i18n("CLN client private key (PEM)"),required:false,masked:true,default:''}),rotateToken:sdk.Value.toggle({name:i18n("Rotate access token"),default:false})})
export const configure=sdk.Action.withInput('configure',async()=>({name:i18n('Configure test app'),description:i18n('Configure this isolated test instance while stopped.'),warning:i18n('Experimental and unaudited. Back up before changing settings.'),allowedStatuses:'only-stopped',group:null,visibility:'enabled',access:'user'}),spec,async()=>{const saved=await store.read().once();const c=saved?.configuration?JSON.parse(saved.configuration):{};return {regtest:c.network==='regtest',pruned:!!c.pruned,rpc_url:c.rpc_url||'',rpc_user:c.rpc_user||'',rpc_password:c.rpc_password||'',sweep_address:c.sweep_address||'',recipient_keys:(c.recipient_allowlist||[]).join(', '),lightning:!!c.cln,cln_uri:c.cln?.uri||'',hold_uri:c.cln?.hold_uri||'',ca:c.cln?.ca||'',client_cert:c.cln?.client_cert||'',client_key:c.cln?.client_key||'',rotateToken:false}},async({effects,input})=>{
 const old=await store.read().once();const previous=old?.configuration?JSON.parse(old.configuration):{}
 const c={...previous,network:input.regtest?'regtest':'bitcoin',pruned:input.pruned,rpc_url:(input.rpc_url||'').trim(),rpc_user:input.rpc_user||'',rpc_password:input.rpc_password||'',sweep_address:input.sweep_address.trim(),recipient_allowlist:(input.recipient_keys||'').split(/[\s,]+/).filter(Boolean),cln:input.lightning?{uri:(input.cln_uri||'').trim(),hold_uri:(input.hold_uri||'').trim(),ca:input.ca||'',client_cert:input.client_cert||'',client_key:input.client_key||''}:null,}
 if(JSON.stringify(c).length>65536)throw new Error(i18n('Configuration too large'))
 const token=old?.token&&!input.rotateToken?old.token:utils.getDefaultString({charset:'0-9,a-f',len:64})
 const postgres=old?.postgres||utils.getDefaultString({charset:'a-z,A-Z,0-9',len:48})
 await sdk.SubContainer.withTemp(effects,{imageId:'app'},sdk.Mounts.of(),'validate-settings',async sub=>{await sub.execFail(['python3','/opt/startos/check-settings.py','ark'],{input:JSON.stringify(c)},15000)})
 await store.merge(effects,{configuration:JSON.stringify(c),token,postgres})
 return {version:'1',title:i18n('Configuration saved'),message:i18n('Start the app. Keep this credential private.'),result:{type:'single',name:i18n('Access token'),description:null,value:token,masked:true,copyable:true,qr:false}}
})
const inspect=sdk.Action.withoutInput('connection-info',async()=>({name:i18n('Funding balances'),description:i18n('Connection details and funding information'),warning:i18n('Keep these details private'),allowedStatuses:'only-running',group:null,visibility:'enabled',access:'user'}),async({effects})=>{const value=await sdk.SubContainer.withTemp(effects,{imageId:'app'},sdk.Mounts.of().mountVolume({volumeId:'main',subpath:null,mountpoint:'/data',readonly:true}),'connection-info',async sub=>String((await sub.execFail(["paperclip-asp", "rpc", "wallet"],{},15000)).stdout));return {version:'1',title:i18n('Funding balances'),message:i18n('Keep these details private'),result:{type:'single',name:i18n('Funding balances'),description:null,value,masked:false,copyable:true,qr:false}}})
const importCln=sdk.Action.withInput('import-cln',async()=>({name:'Import CLN connection',description:'Paste the private bundle from CLN > Connect Ark server. Existing Ark settings are kept.',warning:'Only import credentials from your own trusted CLN node.',allowedStatuses:'only-stopped',group:null,visibility:'enabled',access:'user'}),sdk.InputSpec.of({bundle:sdk.Value.text({name:'Private CLN connection bundle',required:true,masked:true,default:''})}),async()=>({bundle:''}),async({effects,input})=>{
 const old=await store.read().once();if(!old?.configuration)throw new Error('Configure the Ark backend first, then import CLN.')
 const value=await sdk.SubContainer.withTemp(effects,{imageId:'app'},sdk.Mounts.of(),'import-cln',async sub=>String((await sub.execFail(['python3','/opt/startos/import-cln.py'],{input:JSON.stringify({configuration:JSON.parse(old.configuration),bundle:input.bundle})},15000)).stdout))
 await store.merge(effects,{configuration:value.trim()})
 return {version:'1',title:'CLN connected',message:'Endpoints and certificates saved; Lightning is enabled. Start Ark. Tokens, wallet keys and other settings were not changed.',result:null}
})
export const actions=sdk.Actions.of().addAction(configure).addAction(inspect).addAction(importCln)
